<strong>Module:</strong>        Developer &raquo;
<strong>Controller:</strong>    Index &raquo;
<strong>Action:</strong>        index


<?php
 	if(isset($this->data)):
 		echo $this->markdown($this->data);
    else:
?>
<table class="table">
<tr>
<th>Fichero</th>
</tr>
<?php foreach ($this->paginator as $file) : ?>
<tr>
    <td><a  href='docs/<?php echo $file;?>'><?php echo $file;?></a></td>
</tr>
<?php endforeach; ?>
</table>
<?php
    endif; 
?>

<?php
 // add at the end of the file after the table
 echo $this->paginationControl(
     // the paginator object
     $this->paginator,
     // the scrolling style
     'sliding',
     // the partial to use to render the control
     array('partial/paginator.phtml', 'Developer'),
     // the route to link to when a user clicks a control link
     array(
         'route' => 'markdown'
     )
 );
 ?>